### ISSUE TITLE
The pre-processed RobotCar images are unavailable

### ISSUE THREAD

**Issue by Walleclipse** [jac99/MinkLocMultimodal#22]
Hi, thanks for your great work.
The pre-processed and downsampled RobotCar images are unavailable [here](https://drive.google.com/file/d/1fnpBW57LVLZxOZU5-dSnuwfdwbfNyxGg/view?usp=share_link). Could you please re-upload to the pre-processed images via Google Drive?
Thanks in advance.

**Comment by jac99** [comment]
Hi, I've fixed the download link in README. Let me know if it works now.
https://drive.google.com/file/d/1jso-Ku7Ip69DVPIjGUTldLf2R4bqdVZD/view?usp=share_link

**Comment by Walleclipse** [comment]
Thank you very much.
It works.
