### ISSUE TITLE
RobotCar images

### ISSUE THREAD

**Issue by Scarletwitchx** [jac99/MinkLocMultimodal#24]
Hi, thanks for your great work.
The pre-processed and downsampled RobotCar images are unavailable [here](https://drive.google.com/file/d/1fnpBW57LVLZxOZU5-dSnuwfdwbfNyxGg/view?usp=share_link). Could you please re-upload to the pre-processed images via Google Drive?
Thanks in advance.

**Comment by jac99** [comment]
Hi, I've fixed the link to the preprocessed and downsampled RobotCar images for training and evaluation of MinkLocMultimodal method. Fixed link (also corrected in the readme): https://drive.google.com/file/d/1g6nWvJ-T-M41MyZTa0oRHIwP7G-cxer6/view?usp=sharing

**Comment by LuXu01** [comment]
Many thanks for your kind and warm help.
