### ISSUE TITLE
About how to get image to lidar dataset?

### ISSUE THREAD

**Issue by LZL-CS** [jac99/MinkLocMultimodal#8]
Hi,
Thanks for your nice work and shared code.
When I need to get the image to correspond to the lidar point cloud, I follow your instruction to run the `generate_rgb_for_lidar.py` script firstly. But the code which showed as below is confused for me:
![1](https://user-images.githubusercontent.com/54640259/139306106-360e0216-587b-498b-be0e-88ba69b14d3c.png)
May I know what are `lidar2image_ndx_path`, `lidar2image_ndx.pickle` and `pickle...`, etc. Do I need to run other scripts to get these files?

**Comment by jac99** [comment]
Yes, indeed there was the problem in the code. I've updated the code and description in the README file. Now generation of training data should work OK. 
Download the updated code from github (changes were made not only in generate_rgb_for_lidar.py script but in some other files as well) and follow instructions in the updated README file. First generate training and evaluation tuples (section: Generate training and evaluation tuples). Then follow instructions in _Downsample RGB images and index RGB images linked with each point cloud_ section. You need to edit the config file first (_config_baseline_multimodal.txt_) and set _dataset_folder_ parameter and _image_path_ (this is the path where downsampled RGB images and lidar2image_ndx.pickle will be saved).

**Comment by LZL-CS** [comment]
> Yes, indeed there was a problem with the code. I've updated the code and description in the README file. Now the generation of training data should work OK. Download the updated code from github (changes were made not only in _generate_rgb_for_lidar.py_ script but in some other files as well) and follow instructions in the updated README file. First generate training and evaluation tuples (section: Generate training and evaluation tuples). Then follow instructions in _Downsample RGB images and index RGB images linked with each point cloud_ section. You need to edit the config file first (_config_baseline_multimodal.txt_) and set _dataset_folder_ parameter and _image_path_ (this is the path where downsampled RGB images and lidar2image_ndx.pickle will be saved). Let me know if it works now.

OK, got it. Thank you very much.

**Comment by LZL-CS** [comment]
https://github.com/jac99/MinkLocMultimodal/blob/683ef1aae35ab1b60f13cefccfdd0e3f9cb9ea6e/scripts/generate_rgb_for_lidar.py#L37
